const STORE={users:'vc_users',current:'vc_current_user',feed:'vc_feed',dms:'vc_dms',assets:'vc_assets'};
const OWNER='dan44ous';
const games=[
{id:1,name:'Neon City Tycoon',genre:'Tycoon',players:124540,likes:94,thumbnail:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=900&q=80'},
{id:2,name:'SkyRaid Battlegrounds',genre:'Action',players:91220,likes:91,thumbnail:'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80'},
{id:3,name:'Dungeon Forge RPG',genre:'RPG',players:78215,likes:96,thumbnail:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=900&q=80'},
{id:4,name:'Velocity Obby Rush',genre:'Obby',players:66430,likes:89,thumbnail:'https://images.unsplash.com/photo-1481487196290-c152efe083f5?auto=format&fit=crop&w=900&q=80'}
];
const $=(id)=>document.getElementById(id);
const getJson=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const setJson=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const users=()=>getJson(STORE.users,[]); const assets=()=>getJson(STORE.assets,[]);
const me=()=>localStorage.getItem(STORE.current); const userByName=(n)=>users().find(u=>u.username===n);
const isOwner=(n=me())=>userByName(n)?.role==='owner'; const isModerator=(n=me())=>['owner','moderator'].includes(userByName(n)?.role);
function bootData(){
 if(!localStorage.getItem(STORE.users)) setJson(STORE.users,[
  {username:OWNER,password:'0000',avatar:`https://api.dicebear.com/9.x/identicon/svg?seed=${OWNER}`,bio:'Platform owner account',friends:['VantaDev'],followers:10000,following:2,role:'owner'},
  {username:'VantaDev',password:'demo',avatar:'https://api.dicebear.com/9.x/identicon/svg?seed=VantaDev',bio:'Platform staff',friends:[OWNER],followers:1123,following:86,role:'moderator'},
  {username:'SkyBuilder',password:'demo',avatar:'https://api.dicebear.com/9.x/identicon/svg?seed=SkyBuilder',bio:'Builder',friends:['VantaDev'],followers:489,following:52,role:'user'}]);
 if(!localStorage.getItem(STORE.feed)) setJson(STORE.feed,[{user:'VantaDev',text:'Creator analytics update just dropped!',time:'Just now'},{user:OWNER,text:'Owner notice: all assets require moderation approval.',time:'1m ago'}]);
 if(!localStorage.getItem(STORE.dms)) setJson(STORE.dms,[]);
 if(!localStorage.getItem(STORE.assets)) setJson(STORE.assets,[{id:crypto.randomUUID(),name:'Starter Banner',type:'image',url:'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',owner:'VantaDev',status:'approved'},{id:crypto.randomUUID(),name:'Cyber Sprint OST',type:'audio',url:'https://example.com/audio/cyber-sprint.mp3',owner:'SkyBuilder',status:'pending'}]);
}
function header(){const w=$('welcome'); if(w){const n=me(); w.textContent=n?`@${n} (${userByName(n)?.role||'user'})`:'Guest';}}
function authActions(){
 $('loginBtn')?.addEventListener('click',()=>{const u=$('loginUser').value.trim(),p=$('loginPass').value; const x=userByName(u); if(!x||x.password!==p)return alert('Invalid'); localStorage.setItem(STORE.current,u); location.reload();});
 $('registerBtn')?.addEventListener('click',()=>{const u=$('regUser').value.trim(),p=$('regPass').value; if(!u||!p)return alert('Need username/password'); const all=users(); if(all.some(x=>x.username.toLowerCase()===u.toLowerCase()))return alert('Username exists'); all.push({username:u,password:p,avatar:$('regAvatar').value.trim()||`https://api.dicebear.com/9.x/identicon/svg?seed=${encodeURIComponent(u)}`,bio:$('regBio').value.trim(),friends:[],followers:0,following:0,role:'user'}); setJson(STORE.users,all); localStorage.setItem(STORE.current,u); location.reload();});
 $('logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem(STORE.current);location.reload();});
 $('changePwBtn')?.addEventListener('click',()=>{const n=me(); if(!n)return alert('Login'); const cur=$('pwCurrent').value,nw=$('pwNew').value; const all=users(); const u=all.find(x=>x.username===n); if(u.password!==cur)return alert('Wrong current password'); u.password=nw; setJson(STORE.users,all); alert('Password changed'); $('pwCurrent').value='';$('pwNew').value='';});
}
function renderGames(id='gameGrid'){const el=$(id); if(!el)return; el.innerHTML=''; games.forEach(g=>{const c=document.createElement('article'); c.className='item'; c.innerHTML=`<img class="thumb" src="${g.thumbnail}" alt="${g.name} thumbnail"><span class="tag">${g.genre}</span><div class="row"><strong>${g.name}</strong><span class="player-count">${g.players.toLocaleString()} playing</span></div><p>${g.likes}% positive ratings</p>`; el.appendChild(c);});}
function fluctuate(){games.forEach(g=>g.players=Math.max(1000,g.players+Math.floor(Math.random()*2800-1200))); renderGames(); const t=$('liveTotalPlayers'); if(t) t.textContent=games.reduce((a,g)=>a+g.players,0).toLocaleString();}
function renderFeed(){const box=$('feedList'); if(!box)return; box.innerHTML=''; getJson(STORE.feed,[]).slice().reverse().forEach(i=>{const d=document.createElement('div'); d.className='item'; d.innerHTML=`<strong>${i.user}</strong><p>${i.text}</p><p>${i.time}</p>`; box.appendChild(d);}); $('postBtn')?.addEventListener('click',()=>{const n=me(),txt=$('postText').value.trim(); if(!n)return alert('Login'); if(!txt)return; const f=getJson(STORE.feed,[]); f.push({user:n,text:txt,time:new Date().toLocaleString()}); setJson(STORE.feed,f); $('postText').value=''; renderFeed();});}
function renderSocial(){const n=me(); const fl=$('friendList'); const dm=$('dmTarget'); const ml=$('messageList'); if(!fl)return; fl.innerHTML=''; if(dm) dm.innerHTML=''; if(!n){fl.innerHTML='<div class="item">Login required.</div>'; return;} const u=userByName(n); (u.friends||[]).forEach(f=>{const d=document.createElement('div'); d.className='item'; d.textContent='@'+f; fl.appendChild(d); if(dm){const o=document.createElement('option');o.value=f;o.textContent=f;dm.appendChild(o);}}); $('addFriendBtn')?.addEventListener('click',()=>{const f=$('friendName').value.trim(); const all=users(); const meU=all.find(x=>x.username===n); const fr=all.find(x=>x.username===f); if(!fr)return alert('User not found'); if(!meU.friends.includes(f))meU.friends.push(f); if(!fr.friends.includes(n))fr.friends.push(n); setJson(STORE.users,all); $('friendName').value=''; renderSocial();});
 const dms=getJson(STORE.dms,[]).filter(m=>m.from===n||m.to===n).reverse().slice(0,8); if(ml){ml.innerHTML=dms.map(m=>`<div class="item"><strong>${m.from}→${m.to}</strong><p>${m.text}</p></div>`).join('')||'<div class="item">No messages.</div>';}
 $('sendDmBtn')?.addEventListener('click',()=>{const to=$('dmTarget')?.value,txt=$('dmText')?.value.trim(); if(!to||!txt)return; const d=getJson(STORE.dms,[]); d.push({from:n,to,text:txt,time:new Date().toLocaleTimeString()}); setJson(STORE.dms,d); $('dmText').value=''; renderSocial();});
}
function renderAssets(){const list=$('assetList'); if(!list)return; list.innerHTML=''; assets().slice().reverse().forEach(a=>{if(!(a.status==='approved'||isModerator()||a.owner===me()))return; const d=document.createElement('div'); d.className='item'; d.innerHTML=`<div class="row"><strong>${a.name}</strong><span class="status-${a.status}">${a.status}</span></div><p>${a.type} • ${a.owner}</p><p>${a.url}</p>`; list.appendChild(d);});
 $('uploadAssetBtn')?.addEventListener('click',()=>{if(!me())return alert('Login'); const type=$('assetType').value,name=$('assetName').value.trim(),url=$('assetUrl').value.trim(); if(!name||!url)return alert('Need name/url'); const all=assets(); all.push({id:crypto.randomUUID(),type,name,url,owner:me(),status:'pending'}); setJson(STORE.assets,all); $('assetName').value='';$('assetUrl').value=''; renderAssets(); renderModeration();});}
function renderModeration(){const mod=$('modQueue'); if(mod){mod.innerHTML=''; if(!isModerator()){mod.innerHTML='<div class="item">Moderator only.</div>';} else {assets().filter(a=>a.status==='pending').forEach(a=>{const d=document.createElement('div'); d.className='item'; d.innerHTML=`<strong>${a.name}</strong><p>${a.type} by ${a.owner}</p><button data-a="${a.id}" class="btn primary">Approve</button> <button data-d="${a.id}" class="btn">Deny</button>`; mod.appendChild(d);}); mod.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>setAsset(b.dataset.a,'approved')); mod.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>setAsset(b.dataset.d,'denied'));}}
 const own=$('ownerTools'); if(own){if(!isOwner())own.innerHTML='<div class="item">Owner only.</div>'; else own.innerHTML=`<div class="item"><input id="modUser" placeholder="Username"><button id="grantModBtn" class="btn">Grant Mod</button><button id="revokeModBtn" class="btn">Revoke Mod</button><button id="approveAllBtn" class="btn primary">Approve All Pending</button></div><div id="userAdminList" class="list"></div>`; if(isOwner()){ $('grantModBtn').onclick=()=>setRole($('modUser').value.trim(),'moderator'); $('revokeModBtn').onclick=()=>setRole($('modUser').value.trim(),'user'); $('approveAllBtn').onclick=()=>{const all=assets();all.forEach(a=>{if(a.status==='pending')a.status='approved'});setJson(STORE.assets,all);renderModeration();renderAssets();}; const ul=$('userAdminList'); ul.innerHTML=users().map(u=>`<div class="item">@${u.username} — ${u.role}</div>`).join(''); }}
 const pending=$('pendingAssets'); if(pending) pending.textContent=assets().filter(a=>a.status==='pending').length;
}
function setAsset(id,status){const all=assets(); const t=all.find(a=>a.id===id); if(t){t.status=status; setJson(STORE.assets,all); renderModeration(); renderAssets();}}
function setRole(u,role){if(!isOwner())return; const all=users(); const t=all.find(x=>x.username===u); if(!t)return alert('User not found'); if(t.username===OWNER&&role!=='owner')return alert('Cannot remove owner role'); t.role=role; setJson(STORE.users,all); renderModeration();}
function init(){bootData(); header(); authActions(); renderGames(); renderFeed(); renderSocial(); renderAssets(); renderModeration(); const t=$('liveTotalPlayers'); if(t)t.textContent=games.reduce((a,g)=>a+g.players,0).toLocaleString(); setInterval(fluctuate,5000);}
window.addEventListener('DOMContentLoaded',init);
